### ISSUE TITLE
Markdown export ignores todo lists

### ISSUE THREAD

**Issue by HalibutGitWiz** [nvim-neorg/neorg#1142]
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.9.4

### Neorg setup

I'm using Astronvim and its Astrocommunity plugin. I get Neorg preconfigured like this (for use with Lazy package manager) :

```
{
  "nvim-neorg/neorg",
  build = ":Neorg sync-parsers",
  dependencies = { "nvim-lua/plenary.nvim" },
  event = "VeryLazy",
  opts = {
    load = {
      ["core.defaults"] = {}, -- Loads default behaviour
      ["core.concealer"] = {}, -- Adds pretty icons to your documents
      ["core.keybinds"] = {}, -- Adds default keybindings
      ["core.completion"] = {
        config = {
          engine = "nvim-cmp",
        },
      }, -- Enables support for completion plugins
      ["core.journal"] = {}, -- Enables support for the journal module
      ["core.dirman"] = { -- Manages Neorg workspaces
        config = {
          workspaces = {
            notes = "~/projects/notes",
          },
        },
      },
    },
  },
}
```

And then I override some of it with my own settings in another file

```
{
    "neorg",
    opts = {
      load = {
        ["core.dirman"] = {
          config = {
            workspaces = {
              notes = "~/Murena/Notes",
            },
            default_workspace = "notes",
          },
        },
        ["core.export"] = {},
        ["core.export.markdown"] = {},
        ["core.concealer"] = {
          config = {
            icon_preset = "diamond",
            icons = {
              todo = {
                on_hold = {
                  icon = "="
                },
                undone = {
                  icon = " "
                },
                uncertain = {
                  icon = "?"
                },
                urgent = {
                  icon = "!"
                }
              }
            }
          }
        }
      },
    },
  },
  { import = "astrocommunity.project.project-nvim" },
}
```

### Actual behavior

Todo items are not exported in Markdown, whatever the state of the todo.

For example this :
```
- (x) Something done
- ( ) Something not done
```

is exported in Markdown as :
```
-  Something done
-  Something not done
```

### Expected behavior

```
- [x] Something done
- [ ] Something not done
```

### Steps to reproduce

Write my example in a norg file, then do `:Neorg export to-file path/to/test.md`
I also tried to specify the format, just in case, with `:Neorg export to-file path/to/test.md markdown` but get the same result.

### Other information

This is exactly the same problem as in #757, from a few months ago.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

I think I understand Lua enough to try, but I've never worked on a Neovim plugin before. How do you setup a Neovim dev environment isolated from your own config ?

**Comment by max397574** [comment]
you want to load the extensions
https://github.com/nvim-neorg/neorg/wiki/Markdown-Export#configuration

**Comment by HalibutGitWiz** [comment]
Oh, I had missed that part of the configuration, sorry.
It works, thanks. :+1:
