### ISSUE TITLE
[BUG] Nested lists inside a task list makes other tasks to not count towards progression

### ISSUE THREAD

**Issue by Je12emy** [nvim-neorg/neorg#201]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.6.0-dev+509-g09e96fe60

### Log Output

[ERROR Mon 22 Nov 2021 09:20:11 PM CST] ...r/start/neorg/lua/neorg/modules/core/keybinds/module.lua:293: Unable to trigger keybind core.gtd.base.views - the keybind does not exist

### Branch

unstable

### Loaded modules

- core.defaults
- core.norg.concealer
- core.norg.dirman
- core.keybinds
- core.norg.completion

### Expected behavior

A list should not prevent other tasks from being counted towards a list progression.

Example

```
* My Task List (1 of 3) [75% complete]
- [ ] Study
    - Make sure you dont procastinate 
- [ ] Clean my room
- [ ] Workout 
```

### Actual behavior

Placing a nested list inside a task item causes it to not count towards progression.

Example:

```
* My Task List (1 of 2) [50% complete]
- [ ] Study
    - Make sure you dont procastinate 
- [ ] Clean my room
- [ ] Workout 
```

Screenshot for reference:

![image](https://user-images.githubusercontent.com/34408108/143177892-fabaf826-75f4-499e-8336-238d707a1ff4.png)

### Help

No

**Comment by mrossinek** [comment]
Hi @Je12emy! Thanks for the bug report. Neorg actually takes a different approach to nesting items which is aligned with how you would create "nested" headings (or subheadings). This makes us independent of whitespace indentation which (in our eyes) is a big benefit :smile: 

Thus, your example should actually look like this:
```norg
* My Task List
- [ ] Study
-- Make sure you dont procastinate 
- [ ] Clean my room
- [ ] Workout 
```
Which renders correctly as per your expected behavior:
```
◈ My Task List (0 of 3) [0% complete]
• [×] Study
 • Make sure you dont procastinate
• [×] Clean my room
• [×] Workout
```

I hope this answers your comment. If so, please feel free to close the issue :+1:

**Comment by Je12emy** [comment]
Thank you! I was too used to Markdown's syntax, lol
