### ISSUE TITLE
Error when installing norg parser (not when installing norg-meta or norg-table)

### ISSUE THREAD

**Issue by ikerurda** [nvim-neorg/neorg#237]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev+22d7dd2ae (wasn't working either in 6.0)

### Branch

master

### Loaded modules

using defaults:
```require('neorg').setup {
    -- Tell Neorg what modules to load
    load = {
        ["core.defaults"] = {}, -- Load all the default modules
        ["core.norg.concealer"] = {}, -- Allows for use of icons
        ["core.norg.dirman"] = { -- Manage your directories with Neorg
            config = {
                workspaces = {
                    my_workspace = "~/neorg"
                }
            }
        }
    },
}
```
but getting error when `:Neorg modules list`:
```lua
[neorg] [ERROR 20:33:20] ...r/start/neorg/lua/neorg/modules/core/neorgcmd/module.lua:286: Unable to execute command :Neorg modules modules - such a com
mand does not exist.
```

(I don't know if it's related)

### Actual behavior

Error when running `:TSInstall norg`
<img width="1792" alt="Screenshot 2021-12-13 at 8 34 39 PM" src="https://user-images.githubusercontent.com/45340417/145876418-02a4b259-2c6a-4ee8-a537-0508a6ef9a5e.png">

### Expected behavior

I expected the parser to be installed

### Other information

`TSInstall norg` fails
`TSInstall norg-table` and `TSInstall norg-meta`don't

### Help

No

### Implementation help

 I wouldn't know how to fix it.

**Comment by katawful** [comment]
`Neorg modules` was renamed to `Neorg module` fyi

**Comment by max397574** [comment]
operating system?

**Comment by danymat** [comment]
Because you're on macOS: https://github.com/nvim-neorg/neorg/issues/74#issuecomment-906627223

**Comment by ikerurda** [comment]
Thank you so much! Yes it was MacOS.

**Comment by danymat** [comment]
I'm glad it works !
