### ISSUE TITLE
Brackets in document.meta break highlighting

### ISSUE THREAD

**Issue by jghauser** [nvim-neorg/neorg#370]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.6.1

### Neorg setup

```
require('neorg').setup {
  load = {
    ['core.defaults'] = {}, -- Load all the default modules
  }
}
```

### Actual behavior

When adding brackets `()` in the value of any variable in `@document.meta`, the text after the brackets is without highlighting and the following line also loses highlighting. See screenshot:
![20220214_15h11m17s_grim](https://user-images.githubusercontent.com/10319377/153880976-cf8299b7-7d16-415f-a13c-aa3f51b1f16a.jpeg)

### Expected behavior

Highlighting doesn't break.

### Steps to reproduce

Add brackets to the value of any variable defined in `@document.meta`.

### Help

No
