### ISSUE TITLE
Missing indentation for items in an array in document.meta

### ISSUE THREAD

**Issue by jghauser** [nvim-neorg/neorg#417]
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.6.1

### Neorg setup

require('neorg').setup {
load = {
["core.defaults"] = {}
}
}

### Actual behavior

Elements in an array in `document.meta` aren't indented more than the other key-value pairs.

```
@document.meta
  categories: [
  this
  that  
  ]
@end[
```

### Expected behavior

Indentation like this:

```
@document.meta
  categories: [
    this
    that  
  ]
@end[
```

### Steps to reproduce

Create a key-value pair in document.meta and have the value be an array. Add items to the array.

### Help

No

**Comment by vhyrro** [comment]
Hey, very sorry for being this late to fix it but a lot of things happened and I was basically unable to do any serious Neorg development for the past two weeks - should be fixed now! Let me know how it works on your end :)

**Comment by jghauser** [comment]
Thanks a ton -- it works perfectly on my end!

And definitely no need to be sorry! This is a volunteer-driven opensource project, and i totally understand when life happens and we have a little less time available. :)
